# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ianmann.utils.custom_model_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', ianmann.utils.custom_model_fields.RequiredIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ianmann.utils.custom_model_fields.RequiredCharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ianmann.utils.custom_model_fields.RequiredCharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ianmann.utils.custom_model_fields.RequiredCharField(max_length=50)),
                ('website_homepage', models.CharField(max_length=200)),
                ('hq_address', ianmann.utils.custom_model_fields.RequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ianmann.utils.custom_model_fields.RequiredCharField(max_length=50)),
                ('region_type', ianmann.utils.custom_model_fields.RequiredCharField(choices=[('ST', 'State'), ('RE', 'Region'), ('PR', 'Province')], default='ST', max_length=2)),
                ('country', ianmann.utils.custom_model_fields.RequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ianmann.utils.custom_model_fields.RequiredCharField(max_length=50)),
                ('city', ianmann.utils.custom_model_fields.RequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=ianmann.utils.custom_model_fields.RequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Region'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=ianmann.utils.custom_model_fields.RequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Street'),
        ),
    ]
