# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ianmann.utils.custom_model_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ianmann.utils.custom_model_fields.RequiredCharField(max_length=50)),
                ('company_website', models.CharField(max_length=200)),
                ('hq_address', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ianmann.utils.custom_model_fields.RequiredCharField(max_length=50)),
                ('organization', ianmann.utils.custom_model_fields.RequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Organization')),
            ],
        ),
    ]
